name = "coloradospringscommunityservice"
compatibility_date = "2025-11-17"
pages_build_output_dir = "dist"

[vars]
SITE_URL = "https://coloradospringscommunityservice.pages.dev"

[[env.production.d1_databases]]
binding = "DB"
database_name = "cospringscs-db"
database_id = "b6f7fd1c-55a4-44a8-b571-cbbd10d3ce47"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "cospringscs-db-preview"
database_id = "3acb55c2-d4b9-43f1-a701-9986cc2a62c4"

[env.preview.vars]
SITE_URL = "https://react-dev.coloradospringscommunityservice.pages.dev"
RESEND_API_KEY = "re_XD1Gw78Y_C678RAKecJmuNsrng8AxhHgb"