interface AttendanceRecord {
  user_name: string; joined_at: string; attended: number; checked_in_at?: string;
}
interface EventDetails {
  title: string; description: string; location: string;
  start_datetime: string; end_datetime: string; organizer: string;
}

export function generateAttendanceHTML(event: EventDetails, participants: AttendanceRecord[]): string {
  const fmt = (s: string) => new Date(s).toLocaleString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' });
  const attendedCount = participants.filter(p => p.attended).length;
  const rate = participants.length > 0 ? ((attendedCount / participants.length) * 100).toFixed(1) : '0';

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Attendance Sheet - ${event.title}</title>
<style>
body{font-family:'Segoe UI',sans-serif;max-width:8.5in;margin:0 auto;padding:20px;background:white;color:#000}
h1{color:#0078d4;font-size:24pt}
.header{text-align:center;margin-bottom:30px;border-bottom:3px solid #0078d4;padding-bottom:20px}
.event-details{background:#f5f5f5;padding:15px;border-radius:5px;margin-bottom:20px;border-left:4px solid #0078d4}
.stats{background:linear-gradient(135deg,#667eea,#764ba2);padding:20px;border-radius:8px;margin-bottom:20px;display:flex;justify-content:space-around;text-align:center}
.stat-number{font-size:36pt;font-weight:bold;color:white;display:block}
.stat-label{color:rgba(255,255,255,.9);font-size:11pt}
table{width:100%;border-collapse:collapse;margin-top:20px;font-size:10pt}
th{background:#0078d4;color:white;padding:12px 8px;text-align:left}
td{padding:14px 8px;border:1px solid #ddd;min-height:40px}
tr:nth-child(even){background:#f9f9f9}
.footer{margin-top:40px;padding-top:20px;border-top:2px solid #ddd;text-align:center;color:#666;font-size:9pt}
@media print{.no-print{display:none}}
</style></head>
<body>
<button class="no-print" style="background:#0078d4;color:white;border:none;padding:12px 24px;font-size:14px;border-radius:4px;cursor:pointer;margin:20px auto;display:block" onclick="window.print()">Print Attendance Sheet</button>
<div class="header"><h1>Attendance Sheet</h1><div style="color:#666">Colorado Springs Community Service Hub</div></div>
<div class="event-details">
  <div><strong>Event:</strong> ${event.title}</div>
  <div><strong>Location:</strong> ${event.location}</div>
  <div><strong>Start:</strong> ${fmt(event.start_datetime)}</div>
  <div><strong>End:</strong> ${fmt(event.end_datetime)}</div>
  <div><strong>Organizer:</strong> ${event.organizer}</div>
  <div><strong>Generated:</strong> ${new Date().toLocaleString()}</div>
</div>
<div class="stats">
  <div><span class="stat-number">${participants.length}</span><span class="stat-label">Registered</span></div>
  <div><span class="stat-number">${attendedCount}</span><span class="stat-label">Attended</span></div>
  <div><span class="stat-number">${rate}%</span><span class="stat-label">Attendance Rate</span></div>
</div>
<table>
<thead><tr><th>#</th><th>Name</th><th>Registered</th><th>Signature</th><th>Present</th></tr></thead>
<tbody>
${participants.map((p, i) => `<tr><td>${i + 1}</td><td><strong>${p.user_name}</strong></td><td>${new Date(p.joined_at).toLocaleDateString()}</td><td></td><td style="text-align:center"><input type="checkbox"></td></tr>`).join('')}
${Array(5).fill(0).map((_, i) => `<tr style="background:#f0f8ff"><td>${participants.length + i + 1}</td><td style="color:#666"><em>Walk-in</em></td><td></td><td></td><td style="text-align:center"><input type="checkbox"></td></tr>`).join('')}
</tbody>
</table>
<div class="footer"><p>Generated by Colorado Springs Community Service Hub on ${new Date().toLocaleString()}</p></div>
</body></html>`;
}

export function downloadAttendanceSheet(event: EventDetails, participants: AttendanceRecord[]): void {
  const html = generateAttendanceHTML(event, participants);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `attendance-${event.title.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}