name: CI
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - React

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependanceies
        run: npm Install
      - name: Lint
        run: npm run lint